package io.neoterm.utils

import android.content.Context
import io.neoterm.R
import io.neoterm.backend.TerminalSession
import io.neoterm.preference.NeoPreference
import io.neoterm.preference.NeoTermPath
import io.neoterm.frontend.floating.TerminalDialog
import java.io.File

/**
 * @author kiva
 */
object PackageUtils {
    fun syncSource() {
        val source = NeoPreference.loadString(R.string.key_package_source, NeoTermPath.DEFAULT_SOURCE)
        val sourceFile = File(NeoTermPath.SOURCE_FILE)
        FileUtils.writeFile(sourceFile, generateSourceFile(source).toByteArray())
    }

    private fun generateSourceFile(source: String): String {
        return StringBuilder().append("# Generated by NeoTerm-Preference\n")
                .append("deb ")
                .append(source)
                .append(" stable main")
                .append("\n")
                .toString()
    }

    fun executeApt(context: Context, subCommand: String, callback: (Int, TerminalDialog) -> Unit) {
        TerminalDialog(context)
                .onFinish(object : TerminalDialog.SessionFinishedCallback {
                    override fun onSessionFinished(dialog: TerminalDialog, finishedSession: TerminalSession?) {
                        val exit = finishedSession?.exitStatus ?: 1
                        callback(exit, dialog)
                    }
                })
                .imeEnabled(true)
                .execute(NeoTermPath.APT_BIN_PATH, arrayOf("apt", subCommand))
                .show("apt $subCommand")
    }
}