package io.neoterm.ui.settings

import android.os.Bundle
import android.support.v7.app.AlertDialog
import android.support.v7.app.AppCompatPreferenceActivity
import android.view.MenuItem
import io.neoterm.R
import io.neoterm.customize.NeoTermPath
import io.neoterm.preference.NeoPreference
import io.neoterm.utils.FileUtils
import java.io.File

/**
 * @author kiva
 */
class PackageSettingsActivity : AppCompatPreferenceActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        supportActionBar.title = getString(R.string.package_settings)
        supportActionBar.setDisplayHomeAsUpEnabled(true)
        addPreferencesFromResource(R.xml.settings_package)

        val preference = findPreference(getString(R.string.key_package_source))
        preference.summary = NeoPreference.loadString(R.string.key_package_source, NeoTermPath.DEFAULT_SOURCE)

        preference.setOnPreferenceChangeListener { preference, newValue ->
            val newSource = newValue as String
            preference.summary = newSource
            if (newSource.isNotEmpty()) {
                val sourceFile = File(NeoTermPath.SOURCE_FILE)
                FileUtils.writeFile(sourceFile, generateSourceFile(newSource).toByteArray())

                AlertDialog.Builder(this@PackageSettingsActivity)
                        .setMessage(R.string.source_changed)
                        .setPositiveButton(android.R.string.yes, null)
                        .show()
            }
            return@setOnPreferenceChangeListener true
        }
    }

    private fun generateSourceFile(source: String): String {
        return StringBuilder().append("# Generated by NeoTerm-Preference\n")
                .append("deb ")
                .append(source)
                .append(" stable main")
                .append("\n")
                .toString()
    }

    override fun onBuildHeaders(target: MutableList<Header>?) {
    }

    override fun onOptionsItemSelected(item: MenuItem?): Boolean {
        when (item?.itemId) {
            android.R.id.home ->
                finish()
        }
        return super.onOptionsItemSelected(item)
    }
}